from unittest import TestCase
from unittest.mock import MagicMock

from dataforseo_sdk.competitors.competitor_service import CompetitorService


MOCK_VALID_RESPONSE_DOMAIN_COMPETITORS = {
    "version": "0.1.20220216",
    "status_code": 20000,
    "status_message": "Ok.",
    "time": "7.5300 sec.",
    "cost": 0.02,
    "tasks_count": 1,
    "tasks_error": 0,
    "tasks": [
        {
            "id": "02212018-3334-0131-0000-ae0c8d8dc965",
            "status_code": 20000,
            "status_message": "Ok.",
            "time": "7.3481 sec.",
            "cost": 0.02,
            "result_count": 1,
            "path": ["v3", "dataforseo_labs", "competitors_domain", "live"],
            "data": {
                "api": "dataforseo_labs",
                "function": "competitors_domain",
                "target": "afishingaddiction.com",
                "location_code": 2840,
                "language_code": "en",
            },
            "result": [
                {
                    "target": "afishingaddiction.com",
                    "location_code": 2840,
                    "language_code": "en",
                    "total_count": 14287,
                    "items_count": 100,
                    "items": [
                        {
                            "domain": "afishingaddiction.com",
                            "avg_position": 28.530165912518854,
                            "sum_position": 37831,
                            "intersections": 1326,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 11,
                                    "pos_2_3": 30,
                                    "pos_4_10": 187,
                                    "pos_11_20": 292,
                                    "pos_21_30": 259,
                                    "pos_31_40": 240,
                                    "pos_41_50": 152,
                                    "pos_51_60": 71,
                                    "pos_61_70": 29,
                                    "pos_71_80": 27,
                                    "pos_81_90": 18,
                                    "pos_91_100": 8,
                                    "etv": 2811.3100450262427,
                                    "impressions_etv": 31.600143116433173,
                                    "count": 1324,
                                    "estimated_paid_traffic_cost": 1286.1409617953468,
                                    "is_new": 394,
                                    "is_up": 673,
                                    "is_down": 515,
                                    "is_lost": 106,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 11,
                                    "pos_2_3": 30,
                                    "pos_4_10": 187,
                                    "pos_11_20": 292,
                                    "pos_21_30": 259,
                                    "pos_31_40": 242,
                                    "pos_41_50": 152,
                                    "pos_51_60": 71,
                                    "pos_61_70": 29,
                                    "pos_71_80": 27,
                                    "pos_81_90": 18,
                                    "pos_91_100": 8,
                                    "etv": 2811.520045019686,
                                    "impressions_etv": 31.600143116433173,
                                    "count": 1326,
                                    "estimated_paid_traffic_cost": 1286.1409617953468,
                                    "is_new": 673,
                                    "is_up": 517,
                                    "is_down": 106,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 11,
                                    "pos_2_3": 30,
                                    "pos_4_10": 187,
                                    "pos_11_20": 292,
                                    "pos_21_30": 259,
                                    "pos_31_40": 242,
                                    "pos_41_50": 152,
                                    "pos_51_60": 71,
                                    "pos_61_70": 29,
                                    "pos_71_80": 27,
                                    "pos_81_90": 18,
                                    "pos_91_100": 8,
                                    "etv": 2811.520045019686,
                                    "impressions_etv": 31.600143116433173,
                                    "count": 1326,
                                    "estimated_paid_traffic_cost": 1286.1409617953468,
                                    "is_new": 673,
                                    "is_up": 517,
                                    "is_down": 106,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                        {
                            "domain": "pinterest.com",
                            "avg_position": 39.94627192982456,
                            "sum_position": 36431,
                            "intersections": 912,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 2413127,
                                    "pos_2_3": 4330997,
                                    "pos_4_10": 16932569,
                                    "pos_11_20": 18416461,
                                    "pos_21_30": 12604640,
                                    "pos_31_40": 9213382,
                                    "pos_41_50": 6850230,
                                    "pos_51_60": 5299166,
                                    "pos_61_70": 4078418,
                                    "pos_71_80": 3118209,
                                    "pos_81_90": 2372716,
                                    "pos_91_100": 1294082,
                                    "etv": 792242295.8871752,
                                    "impressions_etv": 25855035.010240648,
                                    "count": 86924084,
                                    "estimated_paid_traffic_cost": 535610912.2464654,
                                    "is_new": 48223479,
                                    "is_up": 53342366,
                                    "is_down": 13462528,
                                    "is_lost": 15248644,
                                },
                                "paid": {
                                    "pos_1": 41,
                                    "pos_2_3": 19,
                                    "pos_4_10": 2,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 346.1140001863241,
                                    "impressions_etv": 2.9085899591445923,
                                    "count": 62,
                                    "estimated_paid_traffic_cost": 226.2470135614276,
                                    "is_new": 15,
                                    "is_up": 62,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 5,
                                    "pos_2_3": 20,
                                    "pos_4_10": 132,
                                    "pos_11_20": 193,
                                    "pos_21_30": 182,
                                    "pos_31_40": 183,
                                    "pos_41_50": 99,
                                    "pos_51_60": 47,
                                    "pos_61_70": 17,
                                    "pos_71_80": 18,
                                    "pos_81_90": 10,
                                    "pos_91_100": 6,
                                    "etv": 2339.3280825894326,
                                    "impressions_etv": 16.09050315665081,
                                    "count": 912,
                                    "estimated_paid_traffic_cost": 1094.4179633280728,
                                    "is_new": 504,
                                    "is_up": 333,
                                    "is_down": 60,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 2,
                                    "pos_2_3": 5,
                                    "pos_4_10": 59,
                                    "pos_11_20": 179,
                                    "pos_21_30": 149,
                                    "pos_31_40": 119,
                                    "pos_41_50": 100,
                                    "pos_51_60": 101,
                                    "pos_61_70": 76,
                                    "pos_71_80": 51,
                                    "pos_81_90": 47,
                                    "pos_91_100": 24,
                                    "etv": 2055.5588474627584,
                                    "impressions_etv": 12.034029110800475,
                                    "count": 912,
                                    "estimated_paid_traffic_cost": 760.7871019830345,
                                    "is_new": 550,
                                    "is_up": 148,
                                    "is_down": 187,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                        {
                            "domain": "amazon.com",
                            "avg_position": 37.25539160045403,
                            "sum_position": 32822,
                            "intersections": 881,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 9476419,
                                    "pos_2_3": 11968247,
                                    "pos_4_10": 14962320,
                                    "pos_11_20": 13114925,
                                    "pos_21_30": 9469962,
                                    "pos_31_40": 6790701,
                                    "pos_41_50": 4940550,
                                    "pos_51_60": 3782876,
                                    "pos_61_70": 2961700,
                                    "pos_71_80": 2332239,
                                    "pos_81_90": 1816630,
                                    "pos_91_100": 1015976,
                                    "etv": 2347775156.3865747,
                                    "impressions_etv": 303865754.72539747,
                                    "count": 82632591,
                                    "estimated_paid_traffic_cost": 2557303862.454777,
                                    "is_new": 33892932,
                                    "is_up": 37475308,
                                    "is_down": 12475421,
                                    "is_lost": 21861920,
                                },
                                "paid": {
                                    "pos_1": 134621,
                                    "pos_2_3": 44908,
                                    "pos_4_10": 3607,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 2311674.61181888,
                                    "impressions_etv": 682834.0016358308,
                                    "count": 183136,
                                    "estimated_paid_traffic_cost": 4784226.103076189,
                                    "is_new": 60244,
                                    "is_up": 180505,
                                    "is_down": 779,
                                    "is_lost": 892,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 7,
                                    "pos_2_3": 14,
                                    "pos_4_10": 111,
                                    "pos_11_20": 184,
                                    "pos_21_30": 187,
                                    "pos_31_40": 175,
                                    "pos_41_50": 107,
                                    "pos_51_60": 45,
                                    "pos_61_70": 16,
                                    "pos_71_80": 16,
                                    "pos_81_90": 13,
                                    "pos_91_100": 6,
                                    "etv": 2174.7175586782396,
                                    "impressions_etv": 22.573143043089658,
                                    "count": 881,
                                    "estimated_paid_traffic_cost": 1162.0860853383783,
                                    "is_new": 471,
                                    "is_up": 324,
                                    "is_down": 70,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 30,
                                    "pos_2_3": 27,
                                    "pos_4_10": 77,
                                    "pos_11_20": 129,
                                    "pos_21_30": 143,
                                    "pos_31_40": 116,
                                    "pos_41_50": 103,
                                    "pos_51_60": 77,
                                    "pos_61_70": 71,
                                    "pos_71_80": 50,
                                    "pos_81_90": 36,
                                    "pos_91_100": 22,
                                    "etv": 4627.832574578002,
                                    "impressions_etv": 267.0806051385589,
                                    "count": 881,
                                    "estimated_paid_traffic_cost": 3029.7216506570694,
                                    "is_new": 436,
                                    "is_up": 128,
                                    "is_down": 278,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                        {
                            "domain": "shopkarls.com",
                            "avg_position": 24.492045454545455,
                            "sum_position": 21553,
                            "intersections": 880,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 2898,
                                    "pos_2_3": 5360,
                                    "pos_4_10": 15469,
                                    "pos_11_20": 15541,
                                    "pos_21_30": 12957,
                                    "pos_31_40": 11063,
                                    "pos_41_50": 9986,
                                    "pos_51_60": 8958,
                                    "pos_61_70": 7744,
                                    "pos_71_80": 6446,
                                    "pos_81_90": 5521,
                                    "pos_91_100": 3115,
                                    "etv": 880732.2450768519,
                                    "impressions_etv": 33927.378825983964,
                                    "count": 105059,
                                    "estimated_paid_traffic_cost": 642099.1012060068,
                                    "is_new": 28467,
                                    "is_up": 34535,
                                    "is_down": 24795,
                                    "is_lost": 37306,
                                },
                                "paid": {
                                    "pos_1": 9,
                                    "pos_2_3": 2,
                                    "pos_4_10": 1,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 31.16200026869774,
                                    "impressions_etv": 0.06762000173330307,
                                    "count": 12,
                                    "estimated_paid_traffic_cost": 50.23593354225159,
                                    "is_new": 11,
                                    "is_up": 11,
                                    "is_down": 0,
                                    "is_lost": 1,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 2,
                                    "pos_2_3": 20,
                                    "pos_4_10": 134,
                                    "pos_11_20": 188,
                                    "pos_21_30": 170,
                                    "pos_31_40": 163,
                                    "pos_41_50": 110,
                                    "pos_51_60": 43,
                                    "pos_61_70": 19,
                                    "pos_71_80": 14,
                                    "pos_81_90": 13,
                                    "pos_91_100": 4,
                                    "etv": 2214.6745627652854,
                                    "impressions_etv": 21.501272910740227,
                                    "count": 880,
                                    "estimated_paid_traffic_cost": 740.9283189025009,
                                    "is_new": 499,
                                    "is_up": 311,
                                    "is_down": 59,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 23,
                                    "pos_2_3": 75,
                                    "pos_4_10": 165,
                                    "pos_11_20": 207,
                                    "pos_21_30": 134,
                                    "pos_31_40": 96,
                                    "pos_41_50": 72,
                                    "pos_51_60": 51,
                                    "pos_61_70": 24,
                                    "pos_71_80": 18,
                                    "pos_81_90": 9,
                                    "pos_91_100": 6,
                                    "etv": 6108.090051025152,
                                    "impressions_etv": 59.65402993327007,
                                    "count": 880,
                                    "estimated_paid_traffic_cost": 2573.258314704406,
                                    "is_new": 265,
                                    "is_up": 232,
                                    "is_down": 282,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                        {
                            "domain": "bassresource.com",
                            "avg_position": 35.46171428571429,
                            "sum_position": 31029,
                            "intersections": 875,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 2296,
                                    "pos_2_3": 6052,
                                    "pos_4_10": 24644,
                                    "pos_11_20": 29870,
                                    "pos_21_30": 26207,
                                    "pos_31_40": 24500,
                                    "pos_41_50": 22183,
                                    "pos_51_60": 19683,
                                    "pos_61_70": 17212,
                                    "pos_71_80": 14655,
                                    "pos_81_90": 12422,
                                    "pos_91_100": 7037,
                                    "etv": 274525.46732149087,
                                    "impressions_etv": 15917.039759949315,
                                    "count": 206761,
                                    "estimated_paid_traffic_cost": 189686.75546491623,
                                    "is_new": 63014,
                                    "is_up": 68658,
                                    "is_down": 49617,
                                    "is_lost": 73711,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 5,
                                    "pos_2_3": 25,
                                    "pos_4_10": 135,
                                    "pos_11_20": 194,
                                    "pos_21_30": 163,
                                    "pos_31_40": 157,
                                    "pos_41_50": 103,
                                    "pos_51_60": 41,
                                    "pos_61_70": 21,
                                    "pos_71_80": 14,
                                    "pos_81_90": 11,
                                    "pos_91_100": 6,
                                    "etv": 2138.9304811824113,
                                    "impressions_etv": 10.417589880060405,
                                    "count": 875,
                                    "estimated_paid_traffic_cost": 1086.116490265238,
                                    "is_new": 476,
                                    "is_up": 327,
                                    "is_down": 53,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 28,
                                    "pos_2_3": 35,
                                    "pos_4_10": 150,
                                    "pos_11_20": 110,
                                    "pos_21_30": 111,
                                    "pos_31_40": 97,
                                    "pos_41_50": 82,
                                    "pos_51_60": 80,
                                    "pos_61_70": 74,
                                    "pos_71_80": 48,
                                    "pos_81_90": 37,
                                    "pos_91_100": 23,
                                    "etv": 2001.6948012076318,
                                    "impressions_etv": 31.22357929078862,
                                    "count": 875,
                                    "estimated_paid_traffic_cost": 817.4679219679092,
                                    "is_new": 341,
                                    "is_up": 206,
                                    "is_down": 256,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                        {
                            "domain": "wired2fish.com",
                            "avg_position": 24.11543134872418,
                            "sum_position": 19847,
                            "intersections": 823,
                            "full_domain_metrics": {
                                "organic": {
                                    "pos_1": 1648,
                                    "pos_2_3": 3236,
                                    "pos_4_10": 13227,
                                    "pos_11_20": 15087,
                                    "pos_21_30": 12766,
                                    "pos_31_40": 11306,
                                    "pos_41_50": 10303,
                                    "pos_51_60": 9310,
                                    "pos_61_70": 8391,
                                    "pos_71_80": 7501,
                                    "pos_81_90": 6422,
                                    "pos_91_100": 3843,
                                    "etv": 269492.0615404397,
                                    "impressions_etv": 23566.360809764825,
                                    "count": 103040,
                                    "estimated_paid_traffic_cost": 233538.23227676572,
                                    "is_new": 40912,
                                    "is_up": 51679,
                                    "is_down": 19839,
                                    "is_lost": 26243,
                                },
                                "paid": {
                                    "pos_1": 2,
                                    "pos_2_3": 4,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 7.791000127792358,
                                    "impressions_etv": 0,
                                    "count": 6,
                                    "estimated_paid_traffic_cost": 3.367662012577057,
                                    "is_new": 5,
                                    "is_up": 6,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "metrics": {
                                "organic": {
                                    "pos_1": 1,
                                    "pos_2_3": 16,
                                    "pos_4_10": 133,
                                    "pos_11_20": 183,
                                    "pos_21_30": 154,
                                    "pos_31_40": 149,
                                    "pos_41_50": 102,
                                    "pos_51_60": 39,
                                    "pos_61_70": 16,
                                    "pos_71_80": 14,
                                    "pos_81_90": 11,
                                    "pos_91_100": 5,
                                    "etv": 2061.9695584047586,
                                    "impressions_etv": 14.337962915655226,
                                    "count": 823,
                                    "estimated_paid_traffic_cost": 1030.335726932739,
                                    "is_new": 485,
                                    "is_up": 284,
                                    "is_down": 44,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                            "competitor_metrics": {
                                "organic": {
                                    "pos_1": 32,
                                    "pos_2_3": 44,
                                    "pos_4_10": 142,
                                    "pos_11_20": 229,
                                    "pos_21_30": 154,
                                    "pos_31_40": 73,
                                    "pos_41_50": 48,
                                    "pos_51_60": 41,
                                    "pos_61_70": 29,
                                    "pos_71_80": 24,
                                    "pos_81_90": 5,
                                    "pos_91_100": 2,
                                    "etv": 4913.850372014567,
                                    "impressions_etv": 76.78175140963867,
                                    "count": 823,
                                    "estimated_paid_traffic_cost": 2525.2057660407154,
                                    "is_new": 376,
                                    "is_up": 139,
                                    "is_down": 255,
                                    "is_lost": 0,
                                },
                                "paid": {
                                    "pos_1": 0,
                                    "pos_2_3": 0,
                                    "pos_4_10": 0,
                                    "pos_11_20": 0,
                                    "pos_21_30": 0,
                                    "pos_31_40": 0,
                                    "pos_41_50": 0,
                                    "pos_51_60": 0,
                                    "pos_61_70": 0,
                                    "pos_71_80": 0,
                                    "pos_81_90": 0,
                                    "pos_91_100": 0,
                                    "etv": 0,
                                    "impressions_etv": 0,
                                    "count": 0,
                                    "estimated_paid_traffic_cost": 0,
                                    "is_new": 0,
                                    "is_up": 0,
                                    "is_down": 0,
                                    "is_lost": 0,
                                },
                                "local_pack": None,
                                "featured_snippet": None,
                            },
                        },
                    ],
                }
            ],
        }
    ],
}

TEST_API_USERNAME = "username"
TEST_API_PASSWORD = "api_key"


class TestCompetitorService(TestCase):
    def test_domain_competitors(self):
        mock_rest_client = MagicMock()
        mock_rest_client.post.return_value = MOCK_VALID_RESPONSE_DOMAIN_COMPETITORS

        target_domain = "afishingaddiction.com"
        competitor_service = CompetitorService(client=mock_rest_client)
        competitor_service._location_code = 2840
        competitor_service._language_code = "en"

        domain_competitors = competitor_service.domain_competitors(
            target_domain=target_domain
        )

        assert domain_competitors == MOCK_VALID_RESPONSE_DOMAIN_COMPETITORS
